config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, except: %i[edit update] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: :create
  end
  resources :bookmarks, only: :destroy
  resources :reviews, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'This is already in the list' }
end

# validates_uniqueness_of :movie_id, scope: :list_id

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :rating, presence: true, numericality: { only_integer: true, in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])  # tfs
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])  # tfs
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list  # taken from solution
    if @bookmark.save
      # redirect_to bookmark_path(@bookmark)
      redirect_to list_path(@list)  # taken from solution
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new  # taken from solution.
    @review = Review.new
    # @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])  # don't forget the list_id part
    @review.list = @list                 # forgot this bit too
    if @review.save
      redirect_to list_path(@list)
    else
      @bookmark = Bookmark.new           # no idea what this is
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to list_path(@review.list)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <h3>Add a movie to your list</h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, label: "Select a bookmark movie"%>
    <%= f.input :comment %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true%>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="text-warning">Save any kind of movies</h1>
  <h3 class="mt-5">My Lists</h3>
    <%= link_to "Create a movie list", new_list_path %>
<br><br><br>
  <% @lists.each do |list| %>
    <div class="card" style="width: 25rem;">
    <% if list.photo.attached? %>
      <%= cl_image_tag list.photo.key, class: "card-img-top rounded-top" %>
    <% end %>
      <div class="card-body">
        <h5 class="card-title"><%= link_to list.name, list_path(list) %></h5>
      </div>
    </div>
<br>
  <% end %>
<%# <br><br><br>
  <%= cl_image_tag("eom4swgy9vxt6dfksb91.jpg", width: 400, height: 300, crop: :fill) %>
<br><br>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h3 class="mb-3">Create a new list</h3>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
    <% end %>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1><%= @list.name %></h1>
<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo.key, height: 100, crop: :fill %>
<% end %>
  <span class="movie-tag"><%= @list.movies.count %> movie(s) in this list</span>

<br><br>
  <%= link_to "Delete this list", list_path(@list), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>

<br><br><br>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Select a movie" %>
    <%= f.input :comment %>
    <%= f.submit "Add movie" %>
  <% end %>
<br><br><br>

  <% @list.movies.each do |movie| %>
    <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
      <div class="card" style="width: 25rem;">
        <%= image_tag movie.poster_url, alt: movie.title, class: "card-img-top rounded-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= movie.title %> (<%= movie.rating %>)</h5>
          <p class="card-text"><%= movie.overview %></p>
          <p class="text-primary">"<%= bookmark.comment %>"</p>
          <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}, class: 'text-danger' %>
        </div>
      </div>
<br>
  <% end %>

  <h3>Add a review</h3>
  <%= simple_form_for [@list, @review] do |f| %>
    <%= f.input :rating, label: 'Rating out of 5' %>
    <%= f.input :content, label: 'Comment' %>
    <%= f.submit "Add review" %>
  <% end %>
<br><br>
  <h3>Reviews</h3>
  <% @list.reviews.each do |review| %>
    <p class="fw-bold" ><%= review.rating %> stars</p>
    <p><%= review.content %></p>
    <hr>
  <% end %>
<br>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Homepage', lists_path %>
  </div>
</nav>